-- V1：基礎服務項目種子資料（原本包在 DataInitializer 的 count()==0 區塊裡）
-- 對應：BATH_S/L/CS/CL、BLOW_S/L/CS/CL、BASIC/TRIM/AD/HC/PARTIAL/SPECIAL、
-- CHECKIN/CHECKOUT/COMPLETE、GS001~GS012（共 29 項），逐字從 DataInitializer.java
-- 原始碼機械抽取生成，不是手動謄寫。
-- 用 INSERT IGNORE（靠 item_code 的 UNIQUE 限制）確保不論全新資料庫或已有資料的
-- 正式站資料庫執行都安全，已存在的項目會直接跳過，不會報錯也不會產生重複列。

INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BATH_S', '洗澡（小型犬）', '小型犬洗澡服務', 800.0, false, false, 'BATH_SMALL', 10.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BATH_L', '洗澡（大型犬）', '大型犬洗澡服務', 1200.0, false, false, 'BATH_LARGE', 20.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BATH_CS', '洗澡（小貓）', '小貓洗澡服務', 800.0, false, false, 'BATH_CAT_S', 20.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BATH_CL', '洗澡（大貓）', '大貓洗澡服務', 1200.0, false, false, 'BATH_CAT_L', 30.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BLOW_S', '吹毛（小型犬）', '小型犬吹整毛髮', 600.0, false, false, 'BLOW_SMALL', 10.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BLOW_L', '吹毛（大型犬）', '大型犬吹整毛髮', 900.0, false, false, 'BLOW_LARGE', 20.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BLOW_CS', '吹毛（小貓）', '小貓吹整毛髮', 600.0, false, false, 'BLOW_CAT_S', 20.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BLOW_CL', '吹毛（大貓）', '大貓吹整毛髮', 900.0, false, false, 'BLOW_CAT_L', 30.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('BASIC', '基礎美容', '基礎美容套餐服務', 500.0, false, false, 'BASIC', 10.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('TRIM', '剪毛', '全身毛髮修剪造型', 600.0, false, false, 'TRIM', 20.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('AD', 'AD藥浴', '抗菌除蟲藥浴療程', 400.0, false, false, 'AD', 10.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('HC', 'HC護毛', '深層護毛修護療程', 500.0, false, false, 'HC', 15.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('PARTIAL', '局部修剪', '局部毛髮精修', 200.0, false, false, 'PARTIAL', 5.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('SPECIAL', '特殊項目', '其他特殊美容項目', 0.0, false, false, 'SPECIAL', 5.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('CHECKIN', '接待入場', '顧客接待與寵物入場登記', 0.0, false, false, 'CHECKIN', 5.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('CHECKOUT', '接待送出', '服務完成寵物送交顧客', 0.0, false, false, 'CHECKOUT', 5.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('COMPLETE', '完成確認', '整筆服務完成確認', 0.0, false, false, 'COMPLETE', 5.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS001', '指甲修剪磨圓', '包含基本的指甲長度修剪與邊緣圓滑打磨', 200.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS002', '剃腳底屁股毛', '局部毛髮修剪，保持寵物居家清潔與防滑', 150.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS003', '擠肛門腺', '溫和清潔寵物肛門]''腺，減少異味與不適感', 180.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS004', '耳道清潔', '使用寵物專用潔耳液，溫和清除耳垢', 100.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS005', '手工吹整毛髮', '專業美容師手工吹整，打造蓬鬆順滑毛質', 300.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS006', '腳緣修剪', '精修足部線條，讓腳掌看起來圓潤乾淨', 200.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS007', '臉部精緻修容', '根據寵物臉型進行細緻修剪，視覺造型升級', 350.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS008', '舒壓按摩', '舒緩寵物肌肉緊張，降低美容過程的焦慮感', 400.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS009', '天然低敏結構式洗浴', '使用頂級天然低敏洗劑，深層修復受損毛髮', 500.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS010', '護膚潤澤毛髮', '加強皮膚保濕與毛髮毛鱗片滋養', 280.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS011', '毛鱗修復液', '專門針對乾枯毛髮設計的密集修護安瓶精華', 320.0, false, false, 'OTHER', 0.0, true, false);
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer) VALUES ('GS012', '牙齒清潔', '使用寵物酵素牙膏，基本口腔清潔與除垢', 200.0, false, false, 'OTHER', 0.0, true, false);
