-- V2：貓咪套餐化服務項目種子資料（CAT001~CAT026，初體驗12項+單次12項+加購2項）
-- 逐字從 DataInitializer.java 原始碼機械抽取生成。
-- bookable=true：CAT001~024 是主力套餐方案，要出現在 LIFF 預約頁；
-- CAT025/026 是加購項目，bookable=false、discount_eligible=false（在 V6 統一校正）。

INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT001', '小美容-單層毛-初體驗', '精緻洗，單層毛貓咪初次到店價格', 990.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT002', '小美容-雙層毛-初體驗', '精緻洗，雙層毛貓咪初次到店價格', 1150.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT003', '小美容-長毛貓-初體驗', '精緻洗，長毛貓咪初次到店價格', 1400.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT004', '大美容-單層毛-初體驗', '洗+剃，單層毛貓咪初次到店價格', 1980.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT005', '大美容-雙層毛-初體驗', '洗+剃，雙層毛貓咪初次到店價格', 1980.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT006', '大美容-長毛貓-初體驗', '洗+剃，長毛貓咪初次到店價格', 2150.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT007', '頂級專業定制洗護-單層毛-初體驗', '單層毛貓咪初次到店價格', 1800.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT008', '頂級專業定制洗護-雙層毛-初體驗', '雙層毛貓咪初次到店價格', 2150.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT009', '頂級專業定制洗護-長毛貓-初體驗', '長毛貓咪初次到店價格', 2500.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT010', '大美容+定制洗護-單層毛-初體驗', '單層毛貓咪初次到店價格', 2500.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT011', '大美容+定制洗護-雙層毛-初體驗', '雙層毛貓咪初次到店價格', 2500.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT012', '大美容+定制洗護-長毛貓-初體驗', '長毛貓咪初次到店價格', 2700.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT013', '小美容-單層毛-單次', '精緻洗，單層毛貓咪單次服務價格', 1100.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT014', '小美容-雙層毛-單次', '精緻洗，雙層毛貓咪單次服務價格', 1300.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT015', '小美容-長毛貓-單次', '精緻洗，長毛貓咪單次服務價格', 1600.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT016', '大美容-單層毛-單次', '洗+剃，單層毛貓咪單次服務價格', 2200.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT017', '大美容-雙層毛-單次', '洗+剃，雙層毛貓咪單次服務價格', 2200.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT018', '大美容-長毛貓-單次', '洗+剃，長毛貓咪單次服務價格', 2400.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT019', '頂級專業定制洗護-單層毛-單次', '單層毛貓咪單次服務價格', 2000.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT020', '頂級專業定制洗護-雙層毛-單次', '雙層毛貓咪單次服務價格', 2400.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT021', '頂級專業定制洗護-長毛貓-單次', '長毛貓咪單次服務價格', 2800.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT022', '大美容+定制洗護-單層毛-單次', '單層毛貓咪單次服務價格', 2800.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT023', '大美容+定制洗護-雙層毛-單次', '雙層毛貓咪單次服務價格', 2800.0, false, true, 'BATH_CAT_S', 20.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT024', '大美容+定制洗護-長毛貓-單次', '長毛貓咪單次服務價格', 3000.0, false, true, 'BATH_CAT_L', 30.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT025', '牙齒清潔（進階）', '貓咪加購項目', 100.0, false, false, 'OTHER', 0.0, true, false, 'CAT');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('CAT026', '天然草本泥浴', '貓咪加購項目', 1200.0, false, false, 'OTHER', 0.0, true, false, 'CAT');
