-- V4：狗狗套餐化服務項目種子資料（DOG001~DOG036，6體重級距×短毛/長毛×3服務等級）
-- 逐字從 DataInitializer.java 原始碼機械抽取生成，bookable=true（全部是要出現在
-- LIFF 預約頁的主力套餐方案）。

INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG001', '小型犬-短毛-精緻洗', '體重5kg以下，短毛', 700.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG002', '小型犬-短毛-基礎定制調理', '體重5kg以下，短毛（精緻洗+300）', 1000.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG003', '小型犬-短毛-中階定制調理', '體重5kg以下，短毛（精緻洗+500）', 1200.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG004', '小型犬-長毛-精緻洗', '體重5kg以下，長毛', 800.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG005', '小型犬-長毛-基礎定制調理', '體重5kg以下，長毛（精緻洗+300）', 1100.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG006', '小型犬-長毛-中階定制調理', '體重5kg以下，長毛（精緻洗+500）', 1300.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG007', '中小型犬-短毛-精緻洗', '體重6-10kg，短毛', 800.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG008', '中小型犬-短毛-基礎定制調理', '體重6-10kg，短毛（精緻洗+1100）', 1900.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG009', '中小型犬-短毛-中階定制調理', '體重6-10kg，短毛（精緻洗+1300）', 2100.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG010', '中小型犬-長毛-精緻洗', '體重6-10kg，長毛', 1200.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG011', '中小型犬-長毛-基礎定制調理', '體重6-10kg，長毛（精緻洗+1500）', 2700.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG012', '中小型犬-長毛-中階定制調理', '體重6-10kg，長毛（精緻洗+1700）', 2900.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG013', '中型犬-短毛-精緻洗', '體重11-16kg，短毛', 1000.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG014', '中型犬-短毛-基礎定制調理', '體重11-16kg，短毛（精緻洗+1300）', 2300.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG015', '中型犬-短毛-中階定制調理', '體重11-16kg，短毛（精緻洗+1500）', 2500.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG016', '中型犬-長毛-精緻洗', '體重11-16kg，長毛', 1400.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG017', '中型犬-長毛-基礎定制調理', '體重11-16kg，長毛（精緻洗+1700）', 3100.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG018', '中型犬-長毛-中階定制調理', '體重11-16kg，長毛（精緻洗+2000）', 3400.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG019', '中大型犬-短毛-精緻洗', '體重17-22kg，短毛', 1200.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG020', '中大型犬-短毛-基礎定制調理', '體重17-22kg，短毛（精緻洗+1500）', 2700.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG021', '中大型犬-短毛-中階定制調理', '體重17-22kg，短毛（精緻洗+1800）', 3000.0, false, true, 'BATH_SMALL', 10.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG022', '中大型犬-長毛-精緻洗', '體重17-22kg，長毛', 1800.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG023', '中大型犬-長毛-基礎定制調理', '體重17-22kg，長毛（精緻洗+2200）', 4000.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG024', '中大型犬-長毛-中階定制調理', '體重17-22kg，長毛（精緻洗+2600）', 4400.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG025', '大型犬-短毛-精緻洗', '體重23-27kg，短毛', 1600.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG026', '大型犬-短毛-基礎定制調理', '體重23-27kg，短毛（精緻洗+2000）', 3600.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG027', '大型犬-短毛-中階定制調理', '體重23-27kg，短毛（精緻洗+2400）', 4000.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG028', '大型犬-長毛-精緻洗', '體重23-27kg，長毛', 2200.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG029', '大型犬-長毛-基礎定制調理', '體重23-27kg，長毛（精緻洗+2600）', 4800.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG030', '大型犬-長毛-中階定制調理', '體重23-27kg，長毛（精緻洗+3000）', 5200.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG031', '特大型犬-短毛-精緻洗', '體重28-33kg，短毛', 2000.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG032', '特大型犬-短毛-基礎定制調理', '體重28-33kg，短毛（精緻洗+2400）', 4400.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG033', '特大型犬-短毛-中階定制調理', '體重28-33kg，短毛（精緻洗+3000）', 5000.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG034', '特大型犬-長毛-精緻洗', '體重28-33kg，長毛', 2600.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG035', '特大型犬-長毛-基礎定制調理', '體重28-33kg，長毛（精緻洗+3200）', 5800.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
INSERT IGNORE INTO grooming_items (item_code, name, description, price, is_deleted, bookable, performance_category, points, discount_eligible, requires_existing_customer, applicable_pet_type) VALUES ('DOG036', '特大型犬-長毛-中階定制調理', '體重28-33kg，長毛（精緻洗+3800）', 6400.0, false, true, 'BATH_LARGE', 20.0, true, false, 'DOG');
